appearance_thresh: 0.8
fuse_score: true
gmc_method: sparseOptFlow
match_thresh: 0.8
model: auto
new_track_thresh: 0.35
proximity_thresh: 0.65
track_buffer: 90
track_high_thresh: 0.3
track_low_thresh: 0.1
tracker_type: botsort
with_reid: true
